name: A35 Kernel Cloud Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Install gdown
        run: pip3 install gdown

      - name: Download Source
        run: |
          gdown 1dbt4VddgANMIP13bcYUgKgik5hQp0Joa
          unzip SM-A356E_MEA_15_Opensource.zip
          find . -name "Kernel.tar.gz" -exec tar -xf {} \;
          mv Kernel/* . || true

      - name: Build Kernel with KernelSU
        uses: Boilerplate-Lib/kernel-build-action@main
        with:
          arch: arm64
          compiler: clang
          defconfig: s5e8835_defconfig
          kernelsu: true
          kernelsu_version: main
